development:
 adapter: postgresql
 encoding: unicode
 database: development
 host: localhost
 username: postgres
 password:
 port: 5432
test:
 adapter: postgresql
 encoding: unicode
 database: test
 pool: 5
 host: localhost
 username: postgres
 password:
 port: 5432
production:
 adapter: postgresql
 encoding: unicode
 database: production
 pool: 5
 host: localhost
 username: postgres
 password:
 port: 5432
